# Generated by Django 5.2.4 on 2025-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(choices=[('TEC', 'Technical director'), ('SPO', 'Sports director'), ('ASS', 'Assistant coach')], max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='@gmail.com', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='coaches/')),
            ],
        ),
    ]
