# Generated by Django 5.2.4 on 2025-08-03 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('addras', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('image', models.ImageField(upload_to='players/')),
                ('code', models.CharField(editable=False, max_length=5, unique=True)),
                ('dribbling', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('passing', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('shooting', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Pace', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Defense', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('Physical', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('over_rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
